practice185/author/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.user_signin, name='user_signin'),
    path('login/', views.user_login, name='user_login'),
    path('profile/', views.user_profile, name='user_profile'),
    path('profile/edit_profile', views.edit_profile, name='edit_profile'),
    path('profile/pass_change', views.pass_change, name='pass_change'),
    path('posts/', views.show_posts, name='show_posts'),
    path('logout/', views.user_logout, name='user_logout'),
]

practice185/categories/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.add_category, name='add_category'),
]

practice185/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.add_post, name='add_post'),
    path('edit/<int:id>/', views.edit_post, name='edit_post'),
    path('delete/<int:id>', views.detete_post, name='delete_post'),
]

practice185/practice185/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('author/', include('author.urls')),
    path('add_post/', include('posts.urls')),
    path('add_category/', include('categories.urls')),
]

practice185/author/models.py
from django.db import models

# Create your models here.

practice185/categories/models.py
from django.db import models

class CategoryModel(models.Model):
    categoryName = models.CharField(max_length=255)

    def __str__(self):
        return self.categoryName

practice185/posts/models.py
from django.db import models
from categories.models import CategoryModel
from django.contrib.auth.models import User

class PostModel(models.Model):
    taskTitle = models.CharField(max_length=255)
    taskDescription = models.TextField()
    is_completed = models.BooleanField(default=False)
    taskAssignDate = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(CategoryModel)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.taskTitle

practice185/author/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'id' : 'required'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'id' : 'required'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class ChangeUserForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

practice185/categories/forms.py
from django import forms
from .models import CategoryModel

class CategoryForm(forms.ModelForm):
    class Meta:
        model = CategoryModel
        fields = '__all__'

practice185/posts/forms.py
from django import forms
from .models import PostModel

class PostForm(forms.ModelForm):
    class Meta:
        model = PostModel
        exclude = ['author']
        # fields = '__all__'

practice185/author/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import authenticate, login , update_session_auth_hash, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from posts.models import PostModel


def home(request):
    return render(request, 'home.html')

def user_signin(request):
    if request.method == 'POST':
        signin_form = forms.RegistrationForm(request.POST)
        if signin_form.is_valid():
            signin_form.save()
            messages.success(request, 'Account Created Successfully')
            return redirect('user_signin')
    
    else:
        signin_form = forms.RegistrationForm()
    return render(request, 'user_signin.html', {'form' : signin_form, 'type' : 'Sign-in'})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user_name = form.cleaned_data['username']
            user_pass = form.cleaned_data['password']
            user = authenticate(username=user_name, password=user_pass)
            if user is not None:
                messages.success(request, 'Logged in Successfully')
                login(request, user)
                return redirect('user_profile')
            else:
                messages.warning(request, 'Login informtion incorrect')
                return redirect('user_signin')
    else:
        form = AuthenticationForm()
        return render(request, 'user_login.html', {'form' : form, 'type' : 'Log-in'})


@login_required
def user_profile(request):
    user_form = request.user
    return render(request, 'user_profile.html', {'user': user_form, 'type' : 'Profile'})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        profile_form = forms.ChangeUserForm(request.POST, instance = request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile Updated Successfully')
            return redirect('user_profile')
    
    else:
        profile_form = forms.ChangeUserForm(instance = request.user)
    return render(request, 'edit_profile.html', {'form' : profile_form, 'type' : 'Profile-Update'})


def pass_change(request):
    if request.method == 'POST':
        form = SetPasswordForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Password Updated Successfully')
            update_session_auth_hash(request, form.user)
            return redirect('user_profile')
    
    else:
        form = SetPasswordForm(user=request.user)
    return render(request, 'pass_change.html', {'form' : form, 'type' : 'Password-Update'})


@login_required
def show_posts(request):
    posts = PostModel.objects.filter(author = request.user)
    return render(request, 'show_posts.html', {'posts' : posts})


def user_logout(request):
    logout(request)
    messages.success(request, 'Logged out Successfully')
    return redirect('home')

practice185/categories/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth.decorators import login_required

@login_required
def add_category(request):
    if request.method == 'POST':
        category_form = forms.CategoryForm(request.POST)
        if category_form.is_valid():
            category_form.instance.author = request.user
            category_form.save()
            return redirect('add_post')
    else:
      category_form = forms.CategoryForm()

    return render(request, 'categories/add_category.html', {'form2': category_form})

practice185/posts/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from django.contrib.auth.decorators import login_required

@login_required
def add_post(request):
    if request.method == 'POST':
        post_form = forms.PostForm(request.POST)
        if post_form.is_valid():
            post_form.instance.author = request.user
            post_form.save()
            return redirect('show_posts')
    else:
      post_form = forms.PostForm()

    return render(request, 'posts/add_post.html', {'form1': post_form})


@login_required
def edit_post(request, id):
    post = models.PostModel.objects.get(pk=id)
    post_form = forms.PostForm(instance=post)
    if request.method == 'POST':
        post_form = forms.PostForm(request.POST, instance=post)
        if post_form.is_valid():
            post_form.save()
            return redirect('show_posts')

    return render(request, 'posts/add_post.html', {'form1': post_form})


@login_required
def detete_post(request, id):
    try:
        post = models.PostModel.objects.get(pk=id)
        post.delete()
        return redirect('show_posts')
    except models.PostModel.DoesNotExist:
        return render(request, 'posts/task_not_found.html', {'id': id})

practice185/practice185/views.py
from django.shortcuts import render

def base(request):
    return render(request, 'base.html')

def home(request):
    return render(request, 'home.html')

practice185/author/templates/edit_profile.html
{% extends 'base.html' %} 
{% block title %}Update Profile{% endblock %}

{% load crispy_forms_tags %} 

{% block content %}

<form style="width: 50%; margin: auto" method="post">
    <h1>{{type}} page</h1>
    {% csrf_token %} 
    {{form | crispy}}
    <button class="btn btn-warning mb-5">Submit</button>
</form>

{% endblock %}

practice185/author/templates/pass_change.html
{% extends 'base.html' %} 
{% block title %}Update Password{% endblock %}

{% load crispy_forms_tags %} 

{% block content %}

<form style="width: 50%; margin: auto" method="post">
    <h1>{{type}} page</h1>
    {% csrf_token %} 
    {{form | crispy}}
    <button class="btn btn-warning mb-5">Submit</button>
</form>

{% endblock %}

practice185/author/templates/show_posts.html
{% extends 'base.html' %}

{% block title %}Show Posts{% endblock %}

{% block content %}

<div class="container mt-n2">
  <div class="row">
      {% for post in posts %}
          <div class="col-sm-4 mb-4">
              <div class="card mx-1">
                  <div class="card-body">
                      <h5 class="card-title">ID: {{ post.id }}</h5>
                      <p class="card-title">Assigned Date: {{ post.taskAssignDate }}</p>
                      <p class="card-title">Author Name: {{ post.author.first_name}} {{ post.author.last_name}}</p>

                      <p>
                          Category:
                          {% if post.categories.all %}
                              {% for category in post.categories.all %}
                                  <button class="badge bg-secondary" disabled>{{ category.categoryName }}</button>
                              {% endfor %}
                          {% else %}
                              No Categories
                          {% endif %}
                      </p>

                      <p class="card-text">Description: {{ post.taskDescription }}</p>

                      {% if not post.is_completed %}
                          <a href="{% url 'edit_post' post.id %}" class="btn btn-primary">Edit</a>
                          <a href="{% url 'delete_post' post.id %}" class="btn btn-danger">Delete</a>
                      {% else %}
                          <h6>Completed</h6>
                      {% endif %}
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>
</div>

{% endblock %}

practice185/author/templates/user_login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{%  load crispy_forms_tags %}

{% block content %}

<form style="width:50% ; margin : auto" method="post">
    <h1>{{type}} page</h1>
    {% csrf_token %}
    {{form | crispy}}
    <button class="btn btn-primary mb-5">Submit</button>
</form>

{% endblock %}

practice185/author/templates/user_profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}

{%  load crispy_forms_tags %}

{% block content %}
    
    <form method="post" style="width: 50%; margin: auto" novalidate>
        <h1>{{type}} page</h1>
        </br>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username:</label>
            <input type="text" id="id_username" name="username" value="{{ user.username }}" class="form-control" readonly>
        </div>

        </br>

        <div class="form-group">
            <label for="id_first_name">First Name:</label>
            <input type="text" id="id_first_name" name="first_name" value="{{ user.first_name }}" class="form-control" readonly>
        </div>

        </br>

        <div class="form-group">
            <label for="id_last_name">Last Name:</label>
            <input type="text" id="id_last_name" name="last_name" value="{{ user.last_name }}" class="form-control" readonly>
        </div>

        </br>

        <div class="form-group">
            <label for="id_email">Email:</label>
            <input type="email" id="id_email" name="email" value="{{ user.email }}" class="form-control" readonly>
        </div>

        </br>

        <a href="{% url 'edit_profile' %}" class="btn btn-primary btn-sm">Edit Your Profile</a>
        </br></br>
        <a href="{% url 'pass_change' %}" class="btn btn-primary btn-sm">Change Your Password</a>
    </form>

{% endblock %}

practice185/author/templates/user_signin.html
{% extends 'base.html' %}
{% block title %}Signin{% endblock %}

{%  load crispy_forms_tags %}

{% block content %}

<form style="width:50% ; margin : auto" method="post">
    <h1>{{type}} page</h1>
    {% csrf_token %}
    {{form | crispy}}
    <button class="btn btn-primary mb-5">Submit</button>
</br>
    <small> Already have an account <a href="{% url 'user_login' %}">Log-in</a></small>
</form>

{% endblock %}

practice185/categories/templates/categories/add_category.html
{% extends 'base.html' %}

{% block title %}Add Categoryk{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<form method = "post" style = "width:50%; margin:auto;">
  {% csrf_token %}
  {{form2 | crispy}}
  <button class= "btn btn-primary">Add</button>
</form>

{% endblock %}

practice185/posts/templates/posts/add_post.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<form method = "post" style = "width:50%; margin:auto;">
  {% csrf_token %}
  {{form1 | crispy}}
  <button class= "btn btn-primary">Add</button>
</form>

{% endblock %}

practice185/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}FormAPI{% endblock %}</title>
    <!-- Static tag -->
    {% load static %}
    <!-- CSS link here -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Bootstrap link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <!-- Bootstrap navigation bar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
          <button type="button" class="btn btn-outline-warning" style="font-size: 20px; margin-left: 80px; margin-right: 50px;"><strong>Practice-18.5</strong></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" style="color: #ffc107; font-size: 18px; margin-right: 20px;" href="{% url 'home' %}">Home</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" style="color: #ffc107; font-size: 18px; margin-right: 20px;" href="{% url 'add_post' %}">Add Post</a>
                </li>
              {% endif %}
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" style="color: #ffc107; font-size: 18px; margin-right: 20px;" href="{% url 'add_category' %}">Add Category</a>
                </li>
              {% endif %}
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" style="color: #ffc107; font-size: 18px; margin-right: 20px;" href="{% url 'show_posts' %}">Show Posts</a>
                </li>
              {% endif %}
            </ul>
            <form class="d-flex" style="margin-right:50px;">
                <ul class="navbar-nav">
                    {% if request.user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" style="color: White;" href="{% url 'user_profile' %}"><button type="button" class="btn btn-warning"><strong>Profile</strong></button></a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" style="color: White;" href="{% url 'user_logout' %}"><button type="button" class="btn btn-warning"><strong>Log out</strong></button></a>
                      </li>
                    {% else %}
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" style="color: White;" href="{% url 'user_signin' %}"><button type="button" class="btn btn-warning"><strong>Sign in</strong></button></a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" style="color: White;" href="{% url 'user_login' %}"><button type="button" class="btn btn-warning"><strong>Log in</strong></button></a>
                     </li>
                    {% endif %}
                  </ul>
            </form>
          </div>
        </div>
      </nav>

    <br>

    {% for i in messages %}
    <div class="">
      <p class="text-{{i.tags}}">{{i}}</p>
    </div>
    {% endfor %} 

    <!-- Content block -->
    {% block content %}{% endblock %}

    <!-- JS links -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

practice185/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% load static %}

{% block content %}
    <div style="display: flex; align-items: center; justify-content: space-around;  margin-top: 40px; margin-left:140px; width:90%; gap:40px;">
        <div class="col-6" style="margin-right:50px;">
            <h7 class="H1" style="font-size: 30px;">Welcome to</h7>
            <h1 class="H2" style="font-size: 90px; color: #ffc107; text-shadow: 2px 2px 4px rgba(0, 0, 0, 1);">Demo Website</h1>
            <p class="P1">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
            <a class="" style="color: White;" href="{% url 'user_signin' %}"><button type="button" class="btn btn-dark"><strong>Get Started</strong></button></a>
        </div>
        <div class="col-6">
            <img src="{% static 'images/building.png' %}" class="img-fluid" style="width:80%;  margin-top: 55px;" alt="bg"/>
        </div>
    </div>
{% endblock %}